# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, DSI, 2021.

version: '2'

services:
  serve:
    image: nikolaik/python-nodejs:python3.8-nodejs16-slim
    container_name: mkdocs-material-epfl-scheme-serve
    working_dir: /app
    command: sh -c "npm i && pip install mkdocs-material==6.2.8 && npm run watch"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  build:
    image: nikolaik/python-nodejs:python3.8-nodejs16-slim
    container_name: mkdocs-material-epfl-scheme-build
    working_dir: /app
    command: sh -c "npm i && npm run build"
    volumes:
      - .:/app
